server:
  port: 8080
  env: development
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: vote
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m
  max_conn_age: 30m

rabbitmq:
  host: localhost
  port: 5672
  user: guest
  password: guest
  vhost: /
  prefetch_count: 1
  prefetch_size: 0
  global_prefetch_count: 0
  reconnect_delay: 5s
  max_retries: 3
  exchange:
    name: vote
    type: topic
    durable: true
    auto_delete: false
  queues:
    vote_events:
      name: vote_events
      durable: true
      auto_delete: false
      exclusive: false
      no_wait: false
      arguments: {}
    poll_updates:
      name: poll_updates
      durable: true
      auto_delete: false
      exclusive: false
      no_wait: false
      arguments: {}

migration:
  auto_migrate: true

jwt:
  secret_key: "your-super-secret-key-change-this-in-production"
  token_duration: 24h

logging:
  level: info
  format: json
  output: stdout
  sampling:
    initial: 100
    thereafter: 100
  development: true
  disable_caller: false
  disable_stacktrace: false
  encoding: json
  encoder_config:
    time_key: ts
    level_key: level
    name_key: logger
    caller_key: caller
    function_key: function
    stacktrace_key: stacktrace
    line_ending: "\n"
    level_encoder: capital
    time_encoder: iso8601
    duration_encoder: string
    caller_encoder: short

metrics:
  enabled: true
  path: /metrics
  namespace: vote
  subsystem: api
  labels:
    app: vote
    env: development
  buckets:
    - 0.005
    - 0.01
    - 0.025
    - 0.05
    - 0.1
    - 0.25
    - 0.5
    - 1
    - 2.5
    - 5
    - 10 